repositories:
  - name: zitadel
    url: https://charts.zitadel.com

releases:
  - name: zitadel
    namespace: zitadel
    chart: ../../charts/zitadel
    values:
      - values.yaml
      - service:
          annotations:
            # MetalLB static IP
            "metallb.universe.tf/loadBalancerIPs": {{ env "METAL_LB_IP" | default "192.168.1.100" | quote }}
        zitadel:
          configmapConfig:
            Database:
              Postgres:
                Host: {{ env "DB_HOST" | default "db.tuxmai.com" | quote }}
                Port: {{ env "DB_PORT" | default "5432" | quote }}
                Database: {{ env "DB_NAME" | default "zitadel" | quote }}
                User:
                  Username: {{ env "DB_USER" | default "zitadel_user" | quote }}
                Admin:
                  Username: {{ env "DB_ADMIN_USER" | default "zitadel_admin" | quote }}
          # Masterkey for encryption
          masterkey: {{ env "ZITADEL_MASTERKEY" | default "x123456789012345678901234567891y" | quote }}
        # Database passwords
        env:
          - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
            value: {{ env "DB_USER_PASSWORD" | quote }}
          - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
            value: {{ env "DB_ADMIN_PASSWORD" | quote }}
